version: "2"
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE: "cashmanager"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "my-db:/var/lib/mysql"
volumes:
  my-db: